navigation: hello
context: 
  navigation:
    links:
      - text: Home
        link: "/"
        sublinks: []
      - text: About Us
        sublinks:
        - text: Company
          link: "/company"
        - text: Team
          link: "/team"
        - text: FAQ
          link: "/faq"
        - text: Roadmap
          link: "/roadmap"
      - text: Blog
        link: "/blog"
        sublinks: []
      - text: Login
        sublinks:
        - text: Login
          link: "/register"
        - text: Sign Up
          link: "/signup"