name: Icon
context:
  icon: check
  folder: general 
variants:
- name: Check
  context:
    icon: check
    folder: general 
- name: Close
  context:
    icon: close
    folder: general 
  folder: general 
- name: Arrow Simple
  context:
    icon: arrow-simple
    folder: general 
- name: Arrow Link
  context:
    icon: arrow-link
    folder: general 