name: Dropdown
context: 
  text: Label
  name: option
  placeholder: Please choose an option
  options: 
    - item: 
      text: Option A
      name: option
      value: a
      
    - item: 
      text: Option B
      name: option
      value: b